package com.pojo;

// Generated May 10, 2019 2:49:35 PM by Hibernate Tools 3.4.0.CR1

/**
 * Crop generated by hbm2java
 */
public class Crop implements java.io.Serializable {

	private Integer cid;
	private String cname;
	private String cprice;
	private String cquantity;
	private String ctype;

	public Crop() {
	}

	public Crop(String cname, String cprice, String cquantity, String ctype) {
		this.cname = cname;
		this.cprice = cprice;
		this.cquantity = cquantity;
		this.ctype = ctype;
	}

	public Integer getCid() {
		return this.cid;
	}

	public void setCid(Integer cid) {
		this.cid = cid;
	}

	public String getCname() {
		return this.cname;
	}

	public void setCname(String cname) {
		this.cname = cname;
	}

	public String getCprice() {
		return this.cprice;
	}

	public void setCprice(String cprice) {
		this.cprice = cprice;
	}

	public String getCquantity() {
		return this.cquantity;
	}

	public void setCquantity(String cquantity) {
		this.cquantity = cquantity;
	}

	public String getCtype() {
		return this.ctype;
	}

	public void setCtype(String ctype) {
		this.ctype = ctype;
	}

}
