package com.pojo;

// Generated May 10, 2019 2:49:35 PM by Hibernate Tools 3.4.0.CR1

/**
 * Fruits generated by hbm2java
 */
public class Fruits implements java.io.Serializable {

	private Integer fruitid;
	private String fruitname;
	private String fruitquantity;
	private String fruitpriceperkg;
	private String state;
	private String city;

	public Fruits() {
	}

	public Fruits(String fruitname, String fruitquantity, String fruitpriceperkg, String state, String city) {
		this.fruitname = fruitname;
		this.fruitquantity = fruitquantity;
		this.fruitpriceperkg = fruitpriceperkg;
		this.state = state;
		this.city = city;
	}

	public Integer getFruitid() {
		return this.fruitid;
	}

	public void setFruitid(Integer fruitid) {
		this.fruitid = fruitid;
	}

	public String getFruitname() {
		return this.fruitname;
	}

	public void setFruitname(String fruitname) {
		this.fruitname = fruitname;
	}

	public String getFruitquantity() {
		return this.fruitquantity;
	}

	public void setFruitquantity(String fruitquantity) {
		this.fruitquantity = fruitquantity;
	}

	public String getFruitpriceperkg() {
		return this.fruitpriceperkg;
	}

	public void setFruitpriceperkg(String fruitpriceperkg) {
		this.fruitpriceperkg = fruitpriceperkg;
	}

	public String getState() {
		return this.state;
	}

	public void setState(String state) {
		this.state = state;
	}

	public String getCity() {
		return this.city;
	}

	public void setCity(String city) {
		this.city = city;
	}

}
