package com.pojo;

// Generated May 10, 2019 2:49:35 PM by Hibernate Tools 3.4.0.CR1

/**
 * Supplier generated by hbm2java
 */
public class Supplier implements java.io.Serializable {

	private Integer sid;
	private String sname;
	private String semail;
	private String spassword;
	private String saddress;
	private String sphone;
	private String scompany;

	public Supplier() {
	}

	public Supplier(String sname, String semail, String spassword, String saddress, String sphone, String scompany) {
		this.sname = sname;
		this.semail = semail;
		this.spassword = spassword;
		this.saddress = saddress;
		this.sphone = sphone;
		this.scompany = scompany;
	}

	public Integer getSid() {
		return this.sid;
	}

	public void setSid(Integer sid) {
		this.sid = sid;
	}

	public String getSname() {
		return this.sname;
	}

	public void setSname(String sname) {
		this.sname = sname;
	}

	public String getSemail() {
		return this.semail;
	}

	public void setSemail(String semail) {
		this.semail = semail;
	}

	public String getSpassword() {
		return this.spassword;
	}

	public void setSpassword(String spassword) {
		this.spassword = spassword;
	}

	public String getSaddress() {
		return this.saddress;
	}

	public void setSaddress(String saddress) {
		this.saddress = saddress;
	}

	public String getSphone() {
		return this.sphone;
	}

	public void setSphone(String sphone) {
		this.sphone = sphone;
	}

	public String getScompany() {
		return this.scompany;
	}

	public void setScompany(String scompany) {
		this.scompany = scompany;
	}

}
